package Pages;

public class Strings {
    public static final String VALID_EMAIL = "kursqa21@gmail.com";
    public static final String VALID_PASSWORD = "QA21kupujemprodajem";
    public static final String INVALID_EMAIL = "invalid";
    public static final String INVALID_PASSWORD = "invalid";
    public static final String NONEXISTENT_EMAIL = "sdjsljjdl@nesto.com";
    public static final String WELCOME_PAGE_URL = "https://www.kupujemprodajem.com/user.php?action=welcome";
    public static final String WRONG_PAGE_MESSAGE = "Wrong page!";
    public static final String ELEMENT_NOT_PRESENT = "Element not present";
    public static final String VALUES_NOT_MATCHING = "Values not matching";
    public static final String AUTO = "auto";
    public static final String AUTO_NEWLINE = "auto\n";
    public static final String KPB_BLOG = "https://blog.kupujemprodajem.com/";
    public static final String REKLAMIRAJTE_SVOJ_BIZNIS = "https://www.kupujemprodajem.com/malaprivreda";
    public static final String KAKO_DA_POSTAVITE_OGLAS = "https://blog.kupujemprodajem.com/kako-da/kako-da-postavite-prvi-oglas-preko-desktop-sajta/";
    public static final String FACEBOOK = "https://www.facebook.com/KupujemProdajem";
    public static final String LINKEDIN = "https://www.linkedin.com/company/kupujemprodajem-com";
    public static final String INSTAGRAM_LOGIN = "https://www.instagram.com/accounts/login/?next=/kupujemprodajem/";
    public static final String INSTAGRAM_REDIRECT = "https://www.instagram.com/kupujemprodajem/";
    public static final String WELCOME = "welcome";
    public static final String SEARCH = "search";
    public static final String EUR_SIGN = "€";
    public static final String SPACE_NEWLINE_REGEX = " |\\n";
    public static final String WRONG_PRICE_SORT = "Cene nisu sortirane dobro";
    public static final String KRAGUJEVAC = "Kragujevac";
    public static final String NOT_ON_SEARCH_RESULTS = "Ne nalazi se na rezultatima pretrage";
    public static final String SEARCH_KEYWORD_NOT_PRESENT = "Ne sadrzi keyword pretrage";
    public static final String HOME_PAGE = "https://www.kupujemprodajem.com";
    public static final String USER_IS_ON = "User is on ";
    public static final String OPENING_CHROME_DRIVER = "Opening ChromeDriver";
    public static final String AD = "oglas";
    public static final String AD_NOT_FOLLOWED = "Oglas nije zapracen!";
    public static final String NOT_UNFOLLOWED = "Nije otpraceno";
    public static final String LOGIN = "login";
    public static final String INDEX = "index.php";
    public static final String IS_ELEMENT_PRESENT = "Is element present";
    public static final String JS_CLICK = "arguments[0].click()";
    public static final String FAVOURITES = "favorites";
    public static final String EMPTY_STRING = "";
    public static final String LOCATION_ID = "location_id";
    public static final String NONEXISTENT_KEYWORD = "krempita\n";
    public static final String KEYWORD_FOUND_SEARCH_RESULT_VALID = "KEYWORD FOUND, SEARCH RESULT VALID";
}
